FROM openjdk:19-jdk  
# TODO: Choose a java JRE
# TODO:  Add the compiled java (aka bytecode, aka .class)
COPY Main.class Main.class
# TODO: Run the Java with: “java Main” command.
CMD ["java", "Main"]
